# [START cloudbuild_basic_config]
steps:
# Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/project-satheesh/test-artifact-build', '.']

# Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/project-satheesh/test-artifact-build']
